version: '2'

services:
  data:
    container_name: support_data_11
    image: alpine
    command: /bin/sh
    volumes:
      - www-rsync-sync:/var/www/:rw
      - xhgui-rsync-sync:/var/www/xhgui:rw

volumes:
  www-rsync-sync:
    external: true
  xhgui-rsync-sync:
    external: true
